// <auto-generated />
namespace BigSchool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class innit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(innit));
        
        string IMigrationMetadata.Id
        {
            get { return "202107090559364_innit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
